vversion: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  version: 0.2
version: 0.2

phases:
 build:
   commands:
     - echo Build started on `date`
     - npm install
     - npm run build:ssr
 post_build:
   commands:
     - echo Build completed on `date`
     - cp deploy/appspec.yml appspec.yml
artifacts:
 files:
   - dist/**/*
   - appspec.yml
cache:
 paths:
   - '/root/.npm/**/*'